#!/usr/bin/env python3
"""Analyze locally exported Amazon US product JSON files.

This script does not crawl Amazon, call Amazon APIs, or make network requests. It
only reads JSON files generated by amazon_extract.js and writes two Excel files:
keyword heat and market competitor summary.
"""

from __future__ import annotations

import argparse
import json
import re
import statistics
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import pandas as pd

STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "has", "in", "is", "it",
    "its", "of", "on", "or", "that", "the", "to", "was", "were", "with", "your", "you", "our",
    "this", "these", "those", "their", "they", "them", "his", "her", "he", "she", "we", "us",
    "i", "my", "me", "all", "new", "set", "pack", "pcs", "pc", "inch", "inches", "oz", "lb",
    "lbs", "ft", "cm", "mm", "ml", "white", "black", "red", "blue", "green", "pink", "gray",
    "grey", "best", "use", "used", "using", "made", "make", "high", "quality",
}
WORD_RE = re.compile(r"[a-z][a-z0-9]+(?:-[a-z0-9]+)?")


@dataclass(frozen=True)
class Product:
    asin: str
    title: str
    price_value: float | None
    review_count: int | None
    category: str
    rating: float | None


def load_products(json_path: Path) -> list[Product]:
    with json_path.open("r", encoding="utf-8") as file:
        payload = json.load(file)

    raw_products = payload.get("products", payload if isinstance(payload, list) else [])
    products: list[Product] = []
    for item in raw_products:
        if not isinstance(item, dict):
            continue
        products.append(
            Product(
                asin=str(item.get("asin") or "").strip(),
                title=str(item.get("title") or "").strip(),
                price_value=coerce_float(item.get("price_value") or item.get("price")),
                review_count=coerce_int(item.get("review_count") or item.get("reviews")),
                category=str(item.get("category") or "未识别类目").strip() or "未识别类目",
                rating=coerce_float(item.get("rating")),
            )
        )
    return [product for product in products if product.title]


def coerce_float(value: object) -> float | None:
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)):
        return float(value)
    match = re.search(r"\d+(?:\.\d+)?", str(value).replace(",", ""))
    return float(match.group(0)) if match else None


def coerce_int(value: object) -> int | None:
    number = coerce_float(value)
    return int(number) if number is not None else None


def tokenize(title: str) -> list[str]:
    return [word for word in WORD_RE.findall(title.lower()) if word not in STOPWORDS and len(word) > 2]


def build_keyword_heat(products: Sequence[Product]) -> pd.DataFrame:
    word_counter: Counter[str] = Counter()
    asin_by_word: dict[str, set[str]] = defaultdict(set)
    for product in products:
        unique_title_words = set(tokenize(product.title))
        word_counter.update(unique_title_words)
        for word in unique_title_words:
            asin_by_word[word].add(product.asin or product.title)

    rows = []
    for keyword, frequency in word_counter.most_common():
        rows.append(
            {
                "keyword": keyword,
                "frequency": frequency,
                "product_coverage": len(asin_by_word[keyword]),
                "keyword_type": "大词" if frequency >= 3 and len(keyword) <= 12 else "长尾词",
            }
        )
    return pd.DataFrame(rows, columns=["keyword", "frequency", "product_coverage", "keyword_type"])


def build_market_summary(products: Sequence[Product], low_price_threshold: float | None = None) -> pd.DataFrame:
    groups: dict[str, list[Product]] = defaultdict(list)
    for product in products:
        groups[product.category].append(product)

    rows = []
    for category, items in sorted(groups.items()):
        prices = [item.price_value for item in items if item.price_value is not None]
        reviews = [item.review_count for item in items if item.review_count is not None]
        threshold = low_price_threshold if low_price_threshold is not None else (statistics.median(prices) if prices else None)
        low_price_count = sum(1 for price in prices if threshold is not None and price < threshold)
        median_reviews = statistics.median(reviews) if reviews else 0
        average_price = round(statistics.mean(prices), 2) if prices else None
        competition_score = score_competition(len(items), median_reviews, low_price_count)
        rows.append(
            {
                "category": category,
                "product_count": len(items),
                "average_price": average_price,
                "median_reviews": median_reviews,
                "low_price_threshold": threshold,
                "low_price_competitor_count": low_price_count,
                "competition_score": competition_score,
                "competition_level": label_competition(competition_score),
            }
        )
    return pd.DataFrame(rows)


def score_competition(product_count: int, median_reviews: float, low_price_count: int) -> int:
    review_score = min(40, int(median_reviews / 50))
    density_score = min(35, product_count * 3)
    low_price_score = min(25, low_price_count * 4)
    return review_score + density_score + low_price_score


def label_competition(score: int) -> str:
    if score >= 70:
        return "高竞争"
    if score >= 40:
        return "中竞争"
    return "低竞争"


def write_excel(dataframe: pd.DataFrame, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        dataframe.to_excel(writer, index=False, sheet_name="Sheet1")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze local Amazon product JSON exports.")
    parser.add_argument("json_file", type=Path, help="Path to JSON exported by amazon_extract.js")
    parser.add_argument("--output-dir", type=Path, default=Path("output"), help="Directory for Excel outputs")
    parser.add_argument("--low-price-threshold", type=float, default=None, help="Optional absolute low-price threshold")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    products = load_products(args.json_file)
    if not products:
        raise SystemExit("No valid products found in the JSON file.")

    keyword_heat = build_keyword_heat(products)
    market_summary = build_market_summary(products, args.low_price_threshold)
    write_excel(keyword_heat, args.output_dir / "keyword_heat.xlsx")
    write_excel(market_summary, args.output_dir / "market_summary.xlsx")
    print(f"Loaded {len(products)} products")
    print(f"Wrote {args.output_dir / 'keyword_heat.xlsx'}")
    print(f"Wrote {args.output_dir / 'market_summary.xlsx'}")


if __name__ == "__main__":
    main()
